apiVersion: v1
kind: ConfigMap
metadata:
  name: job-configmap
data:
  app2.py: |
    from kubernetes import client, config
    import os
    import psycopg2
    from datetime import datetime

    # Paramètres de connexion à la base de données PostgreSQL 
    host = os.environ.get("DB_HOST")
    database = os.environ.get("DB_DATABASE")
    user = os.environ.get("DB_USER")
    password = os.environ.get("DB_PASSWORD")
    
    def list_namespaces():
        config.load_incluster_config()
        v1 = client.CoreV1Api()
        print("Liste des namespaces:")
        ret = v1.list_namespace()
        for ns in ret.items:
            print(f"- {ns.metadata.name}")

    def list_pod():
        config.load_incluster_config()
        v1 = client.CoreV1Api()
        print("Listing pods with their IPs:")
        ret = v1.list_pod_for_all_namespaces(watch=False)
        for i in ret.items:
            print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))
    
    def insert_data():
        # Connexion à la base de données
        connection = psycopg2.connect(
            host=host,
            database=database,
            user=user,
            password=password
        )
        cursor = connection.cursor()
    
        try:
            # Exemple d'insertion de données avec une colonne de date
            current_date = datetime.now()
            data_to_insert = ("John", "Doe", current_date)
    
            insert_query = "INSERT INTO your_table (first_name, last_name, date_column) VALUES (%s, %s, %s)"
            cursor.execute(insert_query, data_to_insert)
    
            # Valider les changements et fermer la connexion
            connection.commit()
            print("Données insérées avec succès!")
        except (Exception, psycopg2.Error) as error:
            print("Erreur lors de l'insertion des données:", error)
        finally:
            if connection:
                cursor.close()
                connection.close()
                
    if __name__ == "__main__":
        list_namespaces()
        list_pod()
        insert_data()
