apiVersion: v1
kind: ConfigMap
metadata:
  name: job-configmap
data:
  app.py: |
    from kubernetes import client, config

    def list_namespaces():
        config.load_incluster_config()
        v1 = client.CoreV1Api()
        print("Liste des namespaces:")
        ret = v1.list_namespace()
        for ns in ret.items:
            print(f"- {ns.metadata.name}")

    def list_namespaces():
        config.load_incluster_config()
        v1 = client.CoreV1Api()
        print("Listing pods with their IPs:")
        ret = v1.list_pod_for_all_namespaces(watch=False)
        for i in ret.items:
            print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))
    
    if __name__ == "__main__":
        list_namespaces()
        list_pod()
