apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "nodes_conf_extractor.fullname" . }}
  labels:
    {{- include "nodes_conf_extractor.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: {{ include "nodes_conf_extractor.fullname" . }}
              image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command:
                - /bin/sh
                - '-c'
                - kubectl get ns
                - ls -alt
                - python app.py
              volumeMounts:
              - name: config-volume
                mountPath: /app.py
                subPath: app.py
            volumes:
            - name: config-volume
              configMap:
                name: job-configmap
                items:
                - key: app.py
                  path: app.py                
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: {{ include "nodes_conf_extractor.serviceAccountName" . }}
          serviceAccount: {{ include "nodes_conf_extractor.serviceAccountName" . }}
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
