{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodes_conf_extractor.serviceAccountName" . }}
  labels:
    {{- include "nodes_conf_extractor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-all-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["*"]
  resources: ["pods/exec", "pods/portforward"]
  verbs: ["create"]
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nodes_conf_extractor.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nodes_conf_extractor.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: read-all-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
